version: '3.8'

networks:
    mysqlApp:
        external: true
        
services:
  # This is an image from docker hub
  mysql-container:
    image: "mysql"
    volumes:
      - dbData:/app/
    environment:
      - MYSQL_ROOT_PASSWORD=helloWorld123
      - MYSQL_DATABASE=test
    networks:
      - mysqlApp

  # This is not a image from docker hub
  flaskapp:
    build: 
      context: ./backend/ 
      dockerfile: Dockerfile 
    volumes:
      - flaskAppLogData:/app/logs/
    ports:
      - 300:8080
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8080
    depends_on:
      - mysql-container
    networks:
      - mysqlApp

volumes:
  dbData:
  flaskAppLogData:
